config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'restaurants#index'
  resources :restaurants do
    collection do
      get :top # /restaurants/top
      # get :closest # /restaurants/closest
      # get :smokefree # /restaurants/smokefree
    end

    member do
      get :chef # /restaurants/:id/chef
      # get :menu # /restaurants/:id/menu
      # get :cuisine # /restaurants/:id/cuisin
    end

    resources :reviews, only: [:create] # can remove :new page now since form is on show page
    # restaurants/:restaurant_id/reviews/new => reviews#new => C - Form
    # restaurants/:restaurant_id/reviews => reviews#create => C - process the form

    resources :dishes, only: [:new, :create, :edit, :update]
    # restaurants/:restaurant_id/dishes/new => dishes#new => C - Form
    # restaurants/:restaurant_id/dishes => dishes#create => C - process the form
    # restaurants/:restaurant_id/dishes/edit => dishes#edit => U - form
    # restaurants/:restaurant_id/dishes/update => dishes#update => U - process update form
  end

  resources :reviews, only: [:index, :destroy] # /reviews
  resources :dishes, only: [:index, :destroy] # /dishes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :restaurant

  validates :name, presence: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :dishes, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @dish = Dish.new # prepare form for empty dish isntance

    # link the dish to the restaurant
    @dish.restaurant = @restaurant
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @dish = Dish.new(dish_params)
    # connect the new dish with the restaurant
    @dish.restaurant = @restaurant
    if @dish.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  def destroy
    @dish = Dish.find(params[:id])
    @dish.destroy
    redirect_to restaurant_path(@dish.restaurant)
  end

  private

  def dish_params
    params.require(:dish).permit(:name)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  def show
    @review = Review.new
    @review.restaurant = @restaurant
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /restaurants/1
  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /restaurants/1
  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :stars)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new # prepare the form for an emtpy review instance

    # link @review -> @restaurant
    # @review.restaurant_id = params[:restaurant_id] # => dont need this
    @review.restaurant = @restaurant
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      # redirect_to restaurant_path(restaurant)
      redirect_to @restaurant
    else
      # redirect_to new_restaurant_review_path
      render :new # need to find syntax for how to redirect to show page
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/dishes/new.html.erb
<!-- FORM -->
<h2>Create a new dish for <%= @restaurant.name %></h2>

<!-- pass in an array when dealing with nested routes -->
<%= simple_form_for([@restaurant, @dish]) do |f| %>
  <!-- content input -->
  <%= f.input :name %>
  <%= f.button :submit, class: 'btn-primary' %>
  <!-- submit button -->
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantReviews</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :stars %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn-primary' %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Stars</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.stars %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Stars:</strong>
  <%= @restaurant.stars %>
</p>

<h2>Our Menu</h2>
<ul>
  <% @restaurant.dishes.each do |dish| %>
    <li>
      <%= dish.name %> |
      <%= link_to "Remove",
          dish_path(dish),
          method: :delete,
          data: { confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>

<h2>All reviews</h2>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li>
      <%= review.content %> |
      <%= link_to "Remove",
          review_path(review),
          method: :delete,
          data: { confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %> |
<!-- <#%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %> | -->
<%= link_to 'Create a new dish', new_restaurant_dish_path(@restaurant) %>

<!-- FORM -->
<h2>Leave a review for <%= @restaurant.name %></h2>

<!-- pass in an array when dealing with nested routes -->
<%= simple_form_for([@restaurant, @review]) do |f| %>
  <!-- content input -->
  <%= f.input :content %>
  <%= f.button :submit, class: 'btn-primary' %>
  <!-- submit button -->
<% end %>

app/views/reviews/new.html.erb
<!-- FORM -->
<h2>Leave a review for <%= @restaurant.name %></h2>

<!-- pass in an array when dealing with nested routes -->
<%= simple_form_for([@restaurant, @review]) do |f| %>
  <!-- content input -->
  <%= f.input :content %>
  <%= f.button :submit, class: 'btn-primary' %>
  <!-- submit button -->
<% end %>